//
// BestSeller.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BestSeller: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var isFavorites: Bool?
    public var title: String?
    public var priceWithoutDiscount: Double?
    public var discountPrice: Double?
    public var picture: String?

    public init(id: Int? = nil, isFavorites: Bool? = nil, title: String? = nil, priceWithoutDiscount: Double? = nil, discountPrice: Double? = nil, picture: String? = nil) {
        self.id = id
        self.isFavorites = isFavorites
        self.title = title
        self.priceWithoutDiscount = priceWithoutDiscount
        self.discountPrice = discountPrice
        self.picture = picture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isFavorites = "is_favorites"
        case title
        case priceWithoutDiscount = "price_without_discount"
        case discountPrice = "discount_price"
        case picture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isFavorites, forKey: .isFavorites)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(priceWithoutDiscount, forKey: .priceWithoutDiscount)
        try container.encodeIfPresent(discountPrice, forKey: .discountPrice)
        try container.encodeIfPresent(picture, forKey: .picture)
    }
}

