//
// HomeScreen.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeScreen: Codable, JSONEncodable, Hashable {

    public var homeStore: [HomeStore]?
    public var bestSeller: [BestSeller]?

    public init(homeStore: [HomeStore], bestSeller: [BestSeller]) {
        self.homeStore = homeStore
        self.bestSeller = bestSeller
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case homeStore = "home_store"
        case bestSeller = "best_seller"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(homeStore, forKey: .homeStore)
        try container.encode(bestSeller, forKey: .bestSeller)
    }
}

