//
// MyCartBasket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MyCartBasket: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var images: String?
    public var price: Double?
    public var title: String?

    public init(id: Int? = nil, images: String? = nil, price: Double? = nil, title: String? = nil) {
        self.id = id
        self.images = images
        self.price = price
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case images
        case price
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

