//
// MyCart.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MyCart: Codable, JSONEncodable, Hashable {

    public var basket: MyCartBasket?
    public var delivery: String?
    public var id: Int?
    public var total: Double?

    public init(basket: MyCartBasket? = nil, delivery: String? = nil, id: Int? = nil, total: Double? = nil) {
        self.basket = basket
        self.delivery = delivery
        self.id = id
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case basket
        case delivery
        case id
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(basket, forKey: .basket)
        try container.encodeIfPresent(delivery, forKey: .delivery)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

